#!/bin/sh
cd /home/deepak/softwares/pycharm-community-2019.3/bin
export TVM_HOME=/home/deepak/projects/neoai/tvm
export PYTHONPATH=$TVM_HOME/python:$TVM_HOME/topi/python:$TVM_HOME/nnvm/python:${PYTHONPATH}
./pycharm.sh &

